//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using QPCore.Model.Common.Validations;

    public partial class WebElement
    {
       
        public WebElement()
        {  
        }
         
    
        public int elementid { get; set; }

        [Required]
        public int pageid { get; set; }
        [Required]
        [IsNotNumber]
        public string elementaliasname { get; set; }
        public string elementtype { get; set; }
        public string itype { get; set; }
        public string ivalue { get; set; }
        public string framenavigation { get; set; }
        public string command { get; set; }
        public string locationpath { get; set; }
        public string screenshot { get; set; }
        public Nullable<int> elementparentid { get; set; }
        public string applicationsection { get; set; }
        public string value { get; set; }
        public Nullable<bool> isactive { get; set; }
        public int groupid { get; set; }
        public string pagename { get; set; }
        public string groupname { get; set; }

    }
}
